// Frases de prueba compartidas por los tests de seguridad del ayudante.
// Las usan test/router_seguridad_test.dart y test/guia_atajos_test.dart, para
// que el router y el overlay se prueben con exactamente las mismas frases.
//
// REGLA: ante la duda, gana seguridad (ver router_seguridad_test.dart).

/// Temas de seguridad: siempre el motor de reglas.
const Map<String, List<String>> frasesSeguridad = {
  'emergencia directa': [
    'me hundo',
    'nos hundimos',
    'se hunde el bote',
    'se hunde el barco',
    'se hunde el kayak',
    'se hunde la embarcación',
    'se me hundió la lancha',
    'se hunde la lancha',
    'hombre al agua',
    'necesito ayuda urgente',
    'mayday mayday',
    'auxilio me estoy ahogando',
    'se incendió el motor',
    'estoy en peligro',
    'tengo una emergencia',
    'pedido de socorro',
  ],
  'hundimiento (formas, personas y errores de voz)': [
    'me estoy hundiendo',
    'nos estamos hundiendo',
    'mi amigo se hunde en el agua',
    'se hunde',
    'se me unde el bote',
    'me undo',
    'se está hundiendo mi hijo en el río',
    'mi hermano se hunde',
    'se hunden los chicos',
    'nos undimos',
    'se nos hunde la canoa',
    'el barco se hunde',
    'el bote se está hundiendo',
    'estamos undiendo',
    'se undió el velero',
    'se hunde el gomón',
    'la barca se undió',
    'ayuda mi nena se hunde',
  ],
  'agua: caídas, ahogamiento y personas que no salen': [
    'se cayó mi hijo al agua',
    'se cayeron dos pibes al río',
    'mi amigo se tiró al agua y no sale',
    'el nene no sale del agua',
    'no sale a flote',
    'no puede salir del agua',
    'me caí al agua y no puedo subir',
    'se cayó la nena al río',
    'se tiró un hombre al agua desde el puente',
    'no podemos salir del agua',
    'mi hermano no sale a la superficie',
    'se ahoga mi hijo',
    'creo que se está ahogando',
    'se ahogó un pibe en el arroyo',
    'se nos cayó un chico del bote al agua',
  ],
  'agua en la embarcación (cualquier forma)': [
    'la lancha se está llenando de agua',
    'se nos llenó de agua el bote',
    'hace agua',
    'se está llenando de agua',
    'el barco hace agua',
    'entra agua al bote',
    'el kayak se está llenando de agua',
    'se llena de agua la canoa',
    'el bote está entrando agua',
    'entra agua por el casco del barco',
    'se inunda la embarcación',
  ],
  'vuelco de embarcación': [
    'el kayak se da vuelta',
    'se dio vuelta la canoa',
    'se dio vuelta el velero',
    'volcó el gomón',
    'volcamos con la barca',
    'se nos da vuelta el bote',
  ],
  'emergencia indirecta': [
    'podés ayudarme, perdí el ancla y me arrastra la corriente',
    'se dio vuelta el bote',
    'no veo la costa',
    'entra agua al bote y no para',
    'se me cayó un pibe al río',
    'se me apagó el motor y hay tormenta',
    'estoy a la deriva',
    'se rompió el timón en medio del río',
    'quedamos varados sin combustible',
  ],
  'emergencia con urgencia': [
    'dale rápido que se hunde la lancha',
    'apurate que me ahogo',
    'rápido ayuda que se incendia el motor',
    'urgente se hunde el bote dale',
    'estoy en pura angustia se hunde la lancha',
    'apúrate que se da vuelta el bote',
  ],
  'errores de voz': [
    'prefetura',
    'se me ase agua',
    'me allogo',
    'emerjencia en el rio',
    'nesesito ayuda se undio el bote',
    'ayuda se me undio la lancha',
    'llamar a perfectura naval',
    'ase agua la lancha',
  ],
  'perdido y GPS': [
    'estoy perdido',
    'me perdí',
    'estoy perdido en el río',
    'nos perdimos en el arroyo',
    'estoy perdido en la isla y anochece',
    'estoy perdido en el paraná',
    'estoy perdido en el delta',
    'estoy perdido en el uruguay',
    'estoy en la isla perdido, cómo consigo agua?',
    'estoy en el monte perdido',
    'estamos perdidos',
    'nos perdimos',
    'no encuentro la salida',
    'me perdí en las islas',
    'no sé dónde estoy',
    'dónde estoy',
    'cuál es mi ubicación',
    'mandame mi posición gps',
  ],
  'primeros auxilios': [
    'me corté con un anzuelo y sangra mucho',
    'se desmayó mi amigo',
    'me clavé un anzuelo en el dedo',
    'picadura de raya qué hago',
    'me quemé con el motor',
    'tengo hipotermia',
    'golpe de calor',
    'se atragantó',
    'me mordió una víbora',
    'convulsiona',
    'tengo una fractura, qué hago?',
    'algo me picó porque se hincha',
    'creo que me quebré el brazo',
    'se me dislocó el hombro',
    'me picó una avispa y tengo la cara hinchada',
    'se me hincha la mano después de la picadura',
  ],
  // Salud sin emergencia (paso "salud"): nunca se nombra un medicamento; se manda al
  // médico o al farmacéutico y se da el 107/911. La responde SIEMPRE el motor de
  // reglas: una nube podría recetar.
  'salud sin emergencia': [
    'me duele la cabeza, qué tomo',
    'me duele la cabeza',
    'tengo dolor de cabeza',
    'me duele la panza',
    'tengo dolor de estómago',
    'me duele la muela',
    'tengo fiebre',
    'tengo fiebre y tos',
    'me siento mal',
    'me siento descompuesto',
    'estoy engripado',
    'tengo gripe, qué remedio tomo',
    'qué remedio me recomendás para el resfrío',
    'qué pastilla tomo para el dolor',
    'puedo tomar ibuprofeno',
    'cuánto paracetamol puedo tomar',
    'me duele la espalda de remar',
    'tengo náuseas',
    'estoy con diarrea',
    'me mareo en el bote, qué tomo',
    'me duele el pecho',
    'tengo calambres',
    'me duele la garganta',
    'tengo alergia, qué tomo',
    'me duele el oído',
  ],
  'VHF y Prefectura': [
    'canal 16',
    'qué canal uso para pedir auxilio por radio',
    'cómo llamo por vhf a prefectura',
    'teléfono de prefectura naval',
    'frecuencia de emergencia marítima',
    'número de emergencias 106',
    'cómo uso la radio vhf',
    'prefectura naval argentina',
  ],
};

/// Transaccional: puede seguir a acción directa o tienda, pero nunca a Groq.
const List<String> frasesTransaccionales = [
  'cómo pago el viaje',
  'quiero pagar',
  'dónde veo mis cotizaciones',
  'cómo creo un viaje',
  'confirmar pago con mercado pago',
  'cómo cancelo mi reserva',
  'estado de mi viaje',
  'agregar al carrito',
  'pagar con tarjeta',
  'cómo califico al capitán',
];
