include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - scratch/**
    - scripts/**
    - test/**
  errors:
    deprecated_member_use: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    dead_code: ignore

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
    use_build_context_synchronously: false
    use_super_parameters: false
    unnecessary_underscores: false
    unnecessary_to_list_in_spreads: false
