-- =====================================================
-- Tabla de Configuración de Branding
-- =====================================================

-- Crear tabla de configuración de branding si no existe
CREATE TABLE IF NOT EXISTS public.branding_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave TEXT NOT NULL UNIQUE,
    valor TEXT,
    tipo_valor TEXT NOT NULL DEFAULT 'texto',
    descripcion TEXT,
    actualizado_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    actualizado_por UUID REFERENCES auth.users(id)
);

-- Añadir comentarios a la tabla
COMMENT ON TABLE public.branding_config IS 'Tabla de configuración de branding para personalización visual';
COMMENT ON COLUMN public.branding_config.clave IS 'Clave única de configuración (ej: bg_opacity, bg_brightness)';
COMMENT ON COLUMN public.branding_config.valor IS 'Valor de la configuración';
COMMENT ON COLUMN public.branding_config.tipo_valor IS 'Tipo de valor: texto, numero, color_hex, imagen_url, booleano';
COMMENT ON COLUMN public.branding_config.descripcion IS 'Descripción del propósito de la configuración';
COMMENT ON COLUMN public.branding_config.actualizado_at IS 'Fecha de última actualización';
COMMENT ON COLUMN public.branding_config.actualizado_por IS 'ID del usuario que realizó la última actualización';

-- Crear índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS idx_branding_config_clave ON public.branding_config(clave);
CREATE INDEX IF NOT EXISTS idx_branding_config_tipo_valor ON public.branding_config(tipo_valor);
CREATE INDEX IF NOT EXISTS idx_branding_config_actualizado_at ON public.branding_config(actualizado_at);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.branding_config ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad
CREATE POLICY "Usuarios autenticados pueden ver configuración" ON public.branding_config
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Usuarios autenticados pueden insertar configuración" ON public.branding_config
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Usuarios autenticados pueden actualizar configuración" ON public.branding_config
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Permisos
GRANT SELECT, INSERT, UPDATE ON public.branding_config TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE branding_config_id_seq TO authenticated;

-- =====================================================
-- Insertar configuración inicial
-- =====================================================

INSERT INTO public.branding_config (clave, valor, tipo_valor, descripcion) VALUES
    ('bg_opacity', '0.5', 'numero', 'Opacidad del fondo de pantalla (0.0 - 1.0)'),
    ('bg_brightness', '1.0', 'numero', 'Brillo del fondo de pantalla (0.0 - 2.0)'),
    ('bg_url', 'https://ymgsxwfwntbqvguvbhoa.supabase.co/storage/v1/object/public/branding/portada_inicio.jpg', 'imagen_url', 'URL de la imagen de fondo'),
    ('logo_url', NULL, 'imagen_url', 'URL del logo principal'),
    ('favicon_url', NULL, 'imagen_url', 'URL del favicon'),
    ('color_primario', '#0D6EFD', 'color_hex', 'Color primario de la interfaz'),
    ('color_secundario', '#6C757D', 'color_hex', 'Color secundario de la interfaz'),
    ('color_acento', '#198754', 'color_hex', 'Color de acento'),
    ('font_family', 'Roboto', 'texto', 'Fuente principal de la aplicación'),
    ('enable_animations', 'true', 'booleano', 'Habilitar animaciones en la interfaz')
ON CONFLICT (clave) DO UPDATE SET
    valor = EXCLUDED.valor,
    tipo_valor = EXCLUDED.tipo_valor,
    descripcion = EXCLUDED.descripcion,
    actualizado_at = NOW();

-- =====================================================
-- Funciones RPC para Branding
-- =====================================================

-- Función para obtener toda la configuración de branding
CREATE OR REPLACE FUNCTION public.obtener_branding_config()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    config_result jsonb;
BEGIN
    -- Construir objeto JSON con toda la configuración de branding
    SELECT jsonb_object_agg(clave, valor) INTO config_result
    FROM public.branding_config;
    
    RETURN COALESCE(config_result, '{}'::jsonb);
END;
$$;

-- Función para actualizar una configuración específica
CREATE OR REPLACE FUNCTION public.actualizar_branding_config(
    p_clave TEXT,
    p_valor TEXT,
    p_tipo_valor TEXT DEFAULT 'texto',
    p_descripcion TEXT DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_id UUID;
BEGIN
    -- Obtener ID del usuario actual
    user_id := auth.uid();
    
    IF user_id IS NULL THEN
        RAISE EXCEPTION 'Usuario no autenticado';
    END IF;
    
    -- Insertar o actualizar configuración
    INSERT INTO public.branding_config (
        clave, 
        valor, 
        tipo_valor, 
        descripcion,
        actualizado_at,
        actualizado_por
    ) VALUES (
        p_clave,
        p_valor,
        p_tipo_valor,
        p_descripcion,
        NOW(),
        user_id
    )
    ON CONFLICT (clave)
    DO UPDATE SET
        valor = EXCLUDED.valor,
        tipo_valor = EXCLUDED.tipo_valor,
        descripcion = COALESCE(EXCLUDED.descripcion, branding_config.descripcion),
        actualizado_at = NOW(),
        actualizado_por = EXCLUDED.actualizado_por;
    
    RETURN true;
END;
$$;

-- Función para obtener configuración de login específica
CREATE OR REPLACE FUNCTION public.obtener_configuracion_login()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    config_result jsonb;
BEGIN
    -- Construir objeto JSON con configuración específica de login
    SELECT jsonb_build_object(
        'background_url', COALESCE(MAX(CASE WHEN clave = 'bg_url' THEN valor END), NULL),
        'opacity', COALESCE(MAX(CASE WHEN clave = 'bg_opacity' THEN valor END), '0.5')::float,
        'brightness', COALESCE(MAX(CASE WHEN clave = 'bg_brightness' THEN valor END), '1.0')::float,
        'logo_url', COALESCE(MAX(CASE WHEN clave = 'logo_url' THEN valor END), NULL),
        'favicon_url', COALESCE(MAX(CASE WHEN clave = 'favicon_url' THEN valor END), NULL),
        'color_primario', COALESCE(MAX(CASE WHEN clave = 'color_primario' THEN valor END), '#0D6EFD'),
        'color_secundario', COALESCE(MAX(CASE WHEN clave = 'color_secundario' THEN valor END), '#6C757D'),
        'color_acento', COALESCE(MAX(CASE WHEN clave = 'color_acento' THEN valor END), '#198754'),
        'font_family', COALESCE(MAX(CASE WHEN clave = 'font_family' THEN valor END), 'Roboto'),
        'enable_animations', COALESCE(MAX(CASE WHEN clave = 'enable_animations' THEN valor END), 'true')::boolean
    ) INTO config_result
    FROM public.branding_config
    WHERE clave IN (
        'bg_url', 'bg_opacity', 'bg_brightness',
        'logo_url', 'favicon_url', 'color_primario', 
        'color_secundario', 'color_acento', 'font_family',
        'enable_animations'
    );
    
    RETURN config_result;
END;
$$;

-- Permisos para funciones RPC
GRANT EXECUTE ON FUNCTION public.obtener_branding_config() TO authenticated;
GRANT EXECUTE ON FUNCTION public.actualizar_branding_config() TO authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_configuracion_login() TO authenticated;

-- =====================================================
-- Vista para facilitar consultas
-- =====================================================

CREATE OR REPLACE VIEW public.vista_branding_config AS
SELECT 
    id,
    clave,
    valor,
    tipo_valor,
    descripcion,
    actualizado_at,
    actualizado_por
FROM public.branding_config
ORDER BY clave;

-- Permisos para la vista
GRANT SELECT ON public.vista_branding_config TO authenticated;
