-- Actualización de la tabla profiles para el Registro Maestro

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS nombre VARCHAR(255);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS carnet_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS seguro_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS embarcacion_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS es_capitan BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cp INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS provincia VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS capacidad_personas INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS estado VARCHAR(50) DEFAULT 'pendiente';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verificado BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referido VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referido_id UUID;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vencimiento_seguro TIMESTAMP WITH TIME ZONE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vencimiento_carnet TIMESTAMP WITH TIME ZONE;

-- Recargar cache del esquema de PostgREST
NOTIFY pgrst, 'reload schema';
