-- ================================================================
-- FIX BRANDING COMPLETE - CAPITANYA
-- Ejecutar en el SQL Editor de Supabase
-- Resuelve: tabla configuracion_app, RPCs faltantes,
--           vista_gestion_usuarios, politicas Storage 403
-- ================================================================

-- ================================================================
-- 1. TABLA configuracion_app (canonica para BrandingService)
-- ================================================================
CREATE TABLE IF NOT EXISTS public.configuracion_app (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave TEXT NOT NULL UNIQUE,
    valor TEXT
);

-- Agregar columnas faltantes si la tabla ya existia sin ellas
ALTER TABLE public.configuracion_app
    ADD COLUMN IF NOT EXISTS tipo_valor TEXT NOT NULL DEFAULT 'texto';
ALTER TABLE public.configuracion_app
    ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE public.configuracion_app
    ADD COLUMN IF NOT EXISTS actualizado_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE public.configuracion_app
    ADD COLUMN IF NOT EXISTS actualizado_por UUID;

-- Indices
CREATE INDEX IF NOT EXISTS idx_configuracion_app_clave ON public.configuracion_app(clave);

-- RLS
ALTER TABLE public.configuracion_app ENABLE ROW LEVEL SECURITY;

-- Lectura publica (Login puede leer sin autenticacion)
DROP POLICY IF EXISTS "Lectura publica configuracion_app" ON public.configuracion_app;
CREATE POLICY "Lectura publica configuracion_app"
    ON public.configuracion_app FOR SELECT
    TO public
    USING (true);

-- Escritura solo para autenticados
DROP POLICY IF EXISTS "Escritura autenticada configuracion_app" ON public.configuracion_app;
CREATE POLICY "Escritura autenticada configuracion_app"
    ON public.configuracion_app FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Permisos de tabla
GRANT SELECT ON public.configuracion_app TO anon;
GRANT ALL ON public.configuracion_app TO authenticated;

-- ================================================================
-- 2. DATOS INICIALES de configuracion_app
-- ================================================================
INSERT INTO public.configuracion_app (clave, valor, tipo_valor, descripcion) VALUES
    ('login_background_url', NULL,    'imagen_url', 'URL de imagen de fondo del Login'),
    ('login_opacity',        '0.5',   'numero',     'Opacidad del overlay en el Login (0.0-1.0)'),
    ('login_brightness',     '1.0',   'numero',     'Brillo de la imagen de fondo del Login (0.0-2.0)'),
    ('logo_url',             NULL,    'imagen_url', 'URL del logo principal de la app'),
    ('favicon_url',          NULL,    'imagen_url', 'URL del favicon'),
    ('texto_ayuda',          'Bienvenido a Capitan YA' || chr(10) || chr(10) ||
                             '1. Selecciona tu identidad: Pescador o Capitan' || chr(10) ||
                             '2. Elige tu flujo: Ingresar o Registro' || chr(10) ||
                             '3. Ingresa tus credenciales' || chr(10) ||
                             '4. Comienza tu aventura' || chr(10) || chr(10) ||
                             'Para soporte, contacta a: soporte@capitanya.com',
                             'texto_largo', 'Texto del modal de Ayuda en el Login'),
    ('texto_terminos',       'Terminos y Condiciones de CapitanYA' || chr(10) || chr(10) ||
                             '1. Aceptacion de los Terminos' || chr(10) ||
                             'Al usar CapitanYA, aceptas estos terminos y condiciones.' || chr(10) || chr(10) ||
                             '2. Descripcion del Servicio' || chr(10) ||
                             'CapitanYA es una plataforma que conecta pescadores con capitanes para experiencias de pesca unicas.' || chr(10) || chr(10) ||
                             '3. Responsabilidades del Usuario' || chr(10) ||
                             'Los usuarios deben proporcionar informacion veraz y utilizar la plataforma de manera responsable.',
                             'texto_largo', 'Texto del modal de Terminos y Condiciones en el Login'),
    ('color_primario',       '#0066FF','color_hex',  'Color primario de la interfaz'),
    ('color_secundario',     '#FF6600','color_hex',  'Color secundario de la interfaz'),
    ('color_acento',         '#00E676','color_hex',  'Color de acento'),
    ('font_family',          'Roboto', 'texto',      'Fuente principal de la aplicacion')
ON CONFLICT (clave) DO NOTHING;

-- ================================================================
-- 3. RPC: actualizar_configuracion
-- ================================================================
CREATE OR REPLACE FUNCTION public.actualizar_configuracion(
    p_clave       TEXT,
    p_valor       TEXT,
    p_tipo_valor  TEXT DEFAULT 'texto',
    p_descripcion TEXT DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.configuracion_app (clave, valor, tipo_valor, descripcion, actualizado_at, actualizado_por)
    VALUES (p_clave, p_valor, p_tipo_valor, p_descripcion, NOW(), auth.uid())
    ON CONFLICT (clave)
    DO UPDATE SET
        valor         = EXCLUDED.valor,
        tipo_valor    = EXCLUDED.tipo_valor,
        descripcion   = COALESCE(EXCLUDED.descripcion, configuracion_app.descripcion),
        actualizado_at = NOW(),
        actualizado_por = auth.uid();
    RETURN true;
END;
$$;

GRANT EXECUTE ON FUNCTION public.actualizar_configuracion(TEXT, TEXT, TEXT, TEXT) TO authenticated;

-- ================================================================
-- 4. RPC: obtener_configuracion_login
-- ================================================================
CREATE OR REPLACE FUNCTION public.obtener_configuracion_login()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result jsonb;
BEGIN
    SELECT jsonb_build_object(
        'background_url',   MAX(CASE WHEN clave = 'login_background_url' THEN valor END),
        'opacity',          COALESCE(MAX(CASE WHEN clave = 'login_opacity' THEN valor END), '0.5')::float,
        'brightness',       COALESCE(MAX(CASE WHEN clave = 'login_brightness' THEN valor END), '1.0')::float,
        'logo_url',         MAX(CASE WHEN clave = 'logo_url' THEN valor END),
        'favicon_url',      MAX(CASE WHEN clave = 'favicon_url' THEN valor END),
        'color_primario',   COALESCE(MAX(CASE WHEN clave = 'color_primario' THEN valor END), '#0066FF'),
        'color_secundario', COALESCE(MAX(CASE WHEN clave = 'color_secundario' THEN valor END), '#FF6600'),
        'color_acento',     COALESCE(MAX(CASE WHEN clave = 'color_acento' THEN valor END), '#00E676')
    ) INTO result
    FROM public.configuracion_app
    WHERE clave IN (
        'login_background_url','login_opacity','login_brightness',
        'logo_url','favicon_url',
        'color_primario','color_secundario','color_acento'
    );
    RETURN result;
END;
$$;

-- Acceso publico para que el Login (sin sesion) pueda llamarla
GRANT EXECUTE ON FUNCTION public.obtener_configuracion_login() TO anon;
GRANT EXECUTE ON FUNCTION public.obtener_configuracion_login() TO authenticated;

-- ================================================================
-- 5. RPC: obtener_configuracion (por clave unica)
-- ================================================================
CREATE OR REPLACE FUNCTION public.obtener_configuracion(p_clave TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_valor TEXT;
BEGIN
    SELECT valor INTO v_valor FROM public.configuracion_app WHERE clave = p_clave;
    RETURN v_valor;
END;
$$;

GRANT EXECUTE ON FUNCTION public.obtener_configuracion(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.obtener_configuracion(TEXT) TO authenticated;

-- ================================================================
-- 6. VISTA vista_configuracion_branding (usada por getBrandingStream)
-- ================================================================
CREATE OR REPLACE VIEW public.vista_configuracion_branding AS
SELECT
    id,
    clave,
    valor,
    tipo_valor,
    descripcion,
    actualizado_at,
    NULL::TEXT AS categoria,  -- columna de compatibilidad
    NULL::TEXT AS actualizado_por_email,
    NULL::TEXT AS actualizado_por_nombre
FROM public.configuracion_app
ORDER BY clave;

GRANT SELECT ON public.vista_configuracion_branding TO anon;
GRANT SELECT ON public.vista_configuracion_branding TO authenticated;

-- ================================================================
-- 7. VISTA vista_gestion_usuarios
-- ================================================================
-- Solo usa auth.users (profiles no tiene columnas de rol/estado/baneo)
-- Los datos de rol y estado se leen de raw_user_meta_data
CREATE OR REPLACE VIEW public.vista_gestion_usuarios AS
SELECT
    u.id,
    COALESCE(u.raw_user_meta_data->>'nombre', split_part(u.email, '@', 1)) AS nombre,
    u.email,
    COALESCE(u.raw_user_meta_data->>'rol', 'usuario') AS rol,
    COALESCE(u.raw_user_meta_data->>'estado_cuenta', 'activo') AS estado_cuenta,
    COALESCE((u.raw_user_meta_data->>'verificado')::boolean, false) AS verificado,
    NULL::TIMESTAMP WITH TIME ZONE AS fecha_verificacion,
    NULL::TEXT AS motivo_baneo,
    NULL::TIMESTAMP WITH TIME ZONE AS fecha_baneo,
    u.created_at AS creado_at,
    NULL::TEXT AS baneado_por_email,
    COALESCE((u.raw_user_meta_data->>'esta_baneado')::boolean, false) AS esta_baneado,
    COALESCE((u.raw_user_meta_data->>'es_capitan_verificado')::boolean, false) AS es_capitan_verificado
FROM auth.users u;

GRANT SELECT ON public.vista_gestion_usuarios TO authenticated;

-- ================================================================
-- 8. POLICIES STORAGE - Bucket 'branding' (fix error 403)
-- ================================================================

-- Limpiar politicas antiguas del bucket branding
DROP POLICY IF EXISTS "Imagenes publicas de branding son visibles para todos" ON storage.objects;
DROP POLICY IF EXISTS "Usuarios autenticados pueden subir archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Usuarios autenticados pueden actualizar sus archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Usuarios autenticados pueden actualizar archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Usuarios autenticados pueden eliminar sus archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Usuarios autenticados pueden eliminar archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Administradores pueden gestionar todos los archivos de branding" ON storage.objects;
DROP POLICY IF EXISTS "Permitir subida publica a branding" ON storage.objects;
DROP POLICY IF EXISTS "Permitir actualizacion publica a branding" ON storage.objects;
DROP POLICY IF EXISTS "Permitir eliminacion publica a branding" ON storage.objects;

-- SELECT: publico (cualquiera puede ver imagenes de branding)
CREATE POLICY "branding_select_public" ON storage.objects
    FOR SELECT TO public
    USING (bucket_id = 'branding');

-- INSERT: cualquier usuario autenticado puede subir
CREATE POLICY "branding_insert_authenticated" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'branding');

-- UPDATE: cualquier usuario autenticado puede actualizar
CREATE POLICY "branding_update_authenticated" ON storage.objects
    FOR UPDATE TO authenticated
    USING (bucket_id = 'branding');

-- DELETE: cualquier usuario autenticado puede eliminar
CREATE POLICY "branding_delete_authenticated" ON storage.objects
    FOR DELETE TO authenticated
    USING (bucket_id = 'branding');

-- Asegurarse que el bucket branding existe y es publico
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'branding',
    'branding',
    true,
    10485760,
    ARRAY['image/jpeg','image/jpg','image/png','image/gif','image/webp','image/svg+xml']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 10485760,
    allowed_mime_types = ARRAY['image/jpeg','image/jpg','image/png','image/gif','image/webp','image/svg+xml'];

-- ================================================================
-- 9. VERIFICACION FINAL
-- ================================================================
DO $$
BEGIN
    RAISE NOTICE '=== FIX BRANDING COMPLETE ===';
    RAISE NOTICE 'OK: tabla configuracion_app creada/verificada';
    RAISE NOTICE 'OK: RPC actualizar_configuracion disponible';
    RAISE NOTICE 'OK: RPC obtener_configuracion_login disponible';
    RAISE NOTICE 'OK: vista vista_gestion_usuarios creada';
    RAISE NOTICE 'OK: vista vista_configuracion_branding creada';
    RAISE NOTICE 'OK: politicas Storage bucket branding actualizadas';
    RAISE NOTICE 'PENDIENTE: ejecutar hot-reload en Flutter para ver cambios';
END $$;
